### ISSUE TITLE
Sorting by status doesn't work properly

### ISSUE THREAD

**Issue by jasonjoh** [microsoftgraph/msgraph-samples-dashboard#128]
**Describe the bug**
Sorting by the **Status** column doesn't work as expected. Items seem to be randomly placed.

**To Reproduce**
1. Go to dashboard
1. Click the **Status** column

**Expected behavior**
The list is sorted, with all items of a certain status together

**Screenshots**

![image](https://user-images.githubusercontent.com/8966342/86276889-bd681600-bba3-11ea-8945-26b908bd1601.png)

**Additional context**

It would be super helpful to be able to quickly see all the samples that have urgent updates. Sorting like this would do that.

**Comment by MaggieKimani1** [comment]
This was an unnoticed bug.
Definitely looking into it!
Thanks!
