### ISSUE TITLE
Non-owner is shown as an owner

### ISSUE THREAD

**Issue by MIchaelMainer** [microsoftgraph/msgraph-samples-dashboard#145]
**Describe the bug**
It appears that the top three contributors are shown as the SDK owner. One of the three for PHP is not an owner.  Who is an owner? I think anyone with the Admin or Maintain perm could be considered an owner, although we'd have to be comfortable with a GH team as an owner. We could filter non-members of the org from the "owner" list. 

**To Reproduce**
![image](https://user-images.githubusercontent.com/8527305/109538968-908f3a00-7a75-11eb-82ed-ea9ade5e89e9.png)

**Expected behavior**
Only members of the microsoftgraph GH organization are shown in owners field. 
[AB#8350](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8350)

**Comment by MaggieKimani1** [comment]
Yeah I can definitely add that check to filter out non-members of the org from the owner's list.
Thanks for pointing that out.
