### ISSUE TITLE
As a user, I should be able to go to a web url and access the samples dashboard online as opposed to having to clone the repo on my localhost

### ISSUE THREAD

**Issue by bettirosengugi** [microsoftgraph/msgraph-samples-dashboard#56]
Deploy the app to a azure website and create a deployment architecture so that when a PR is merged into Master, it triggers a deployment on the dev environment.

**Comment by andrueastman** [comment]
Closing this as dev environment is now up. 
Production should be up once a pr from dev to master is created and merged in.
